name: Release Notify

on:
  release:
    types:
    - published

jobs:
  notify:
    name: Send job complete notification
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Common Setup
        uses: ./.github/actions/common-setup
        with:
          java-version: 17

      - name: Retrieve Project Name
        run: echo "PROJECT_NAME=$(${{github.workspace}}/gradlew -q printProjectName)" >> $GITHUB_ENV
        id: project_name
      - name: Set release environment
        run: |
          echo "RELEASE_TYPE=release" >> $GITHUB_ENV
          echo "RELEASE_ADDR=https://github.com/${{ github.repository }}/releases/tag/${{ github.ref_name }}" >> $GITHUB_ENV
